# Code Challenges 
This notebook contains the worked out code challenges from the Udemy linear algebra course. 

---
## Code Challenge 1 - Lec. 13
Create 2 4x6 mactrices of random numbers.<br>
Use a for-loop to compute dot products between corresponding columns

In [1]:
import random as rand
import numpy as np

In [6]:
# -- Matrix size
n = 4
m = 6

In [7]:
# -- Generate random matrix with values between -10 and 10
A = np.random.randint(-10, high=10, size=(n,m) )
B = np.random.randint(-10, high=10, size=(n,m) )

In [11]:
print( "A" )
print( "{a}".format(a=A) )
print( "B" )
print( "{b}".format(b=B) )

A
[[ -4   0   7   8   8   3]
 [  1   5 -10  -3 -10   7]
 [  0  -3   2 -10 -10   2]
 [ -9  -7   3  -1  -3  -6]]
B
[[ 4 -8 -3  0 -3  2]
 [-1  1  4  3 -8 -3]
 [ 1 -1 -8  8  6 -5]
 [-8  9  5  8 -1 -8]]


To get the column out of a matrix you can use:<br>
``` python
A[:,i]
```
The colons in the row spot means give me everything in rows, and i represents the column index

In [16]:
c = np.zeros( A.shape[1] )  # --- Initialize a vector to store all dot products
# --- Loop through columns
for i in range(A.shape[1]):
    c[i] = A[:,i].dot(B[:,i])

In [18]:
print("The dot products of the columns are: \n{}".format(c))

The dot products of the columns are: 
[ 55. -55. -62. -97.  -1.  23.]


In [20]:
print("Confirm results: \nRow1 = {}".format((-4*4)+(1*-1)+(0*1)+(-9*-8)) )

Confirm results: 
Row1 = 55
